#!/bin/sh

# sed the riak-cs settings into factory riak.conf and advanced.config

sed -i \
    -e "s|storage_backend = bitcask|storage_backend = multi|" \
    /etc/riak/riak.conf

echo "
buckets.default.allow_mult = true
buckets.default.merge_strategy = 2" \
    >>/etc/riak/riak.conf

sed -i \
    -e "s|]\\.|, \
    {riak_kv, [ \
      {multi_backend, \
          [{be_default,riak_kv_eleveldb_backend, \
               [{max_open_files,20}]}, \
           {be_blocks,riak_kv_bitcask_backend, \
               []}]}, \
      {multi_backend_default,be_default}, \
      {multi_backend_prefix_list,[{<<\"0b:\">>,be_blocks}]}, \
      {storage_backend,riak_kv_multi_backend} \
     ]} \
     ].|" \
     /etc/riak/advanced.config
