#!/bin/bash

ETC=${ETC:-"/etc/riak"}
RIAK_CS_EBIN=${RIAK_CS_EBIN:-"/usr/lib/riak-cs/lib"}
paths_to_add=`for p in ${RIAK_CS_EBIN}/riak_cs*/ebin; do echo -n \\"$p\\",; done | sed 's/,$//'`

# sed the riak-cs settings into factory riak.conf and advanced.config

sed -i \
    -e "s|storage_backend = bitcask|storage_backend = multi|" \
    $ETC/riak.conf

echo "
buckets.default.merge_strategy = 2" \
    >>$ETC/riak.conf

sed -i \
    -e "s|]\\.|, \
    {riak_kv, [ \
      {add_paths, [${paths_to_add}]}, \
      {multi_backend, \
          [{be_default,riak_kv_eleveldb_backend, \
               [{max_open_files,20}]}, \
           {be_blocks,riak_kv_bitcask_backend, \
               []}]}, \
      {multi_backend_default,be_default}, \
      {multi_backend_prefix_list,[{<<\"0b:\">>,be_blocks}]}, \
      {storage_backend,riak_kv_multi_backend} \
     ]} \
     ].|" \
     $ETC/advanced.config
