version: "3.9"
services:

  riak:
    networks:
      net0:
        aliases:
          - riak
    ports:
      - "8087:8087"
      - "8098:8098"
    image: bundle_riak
    deploy:
      replicas: ${RIAK_NODES:-3}

  stanchion:
    depends_on:
      - riak
    networks:
      net0:
        aliases:
          - stanchion
    ports:
      - "8085:8085"
    image: bundle_stanchion
    deploy:
      replicas: 1

  riak_cs:
    depends_on:
      - riak
      - stanchion
    networks:
      net0:
        aliases:
          - riak_cs
    ports:
      - "8080:8080"
      - "8000:8000"
    image: bundle_riak_cs
    deploy:
      replicas: 3

  riak_cs_control:
    depends_on:
      - riak_cs
    networks:
      net0:
        aliases:
          - riak_cs_control
    ports:
      - "8090:8090"
    image: bundle_riak_cs_control

networks:
  net0:
