#! /bin/sh
#
# gen_dev dev4 vars.src vars
#
# Generate an overlay config for devNNN from vars.src and write to vars
#

NAME=$1
TEMPLATE=$2
VARFILE=$3

NODE="rcs-$NAME@127.0.0.1"

SCRIPT_DIR="`dirname $0`/.."
BUILD_ROOT="`cd "$SCRIPT_DIR" && pwd -P`"

NUMBER=${NAME##dev}
RIAKBASE=$((10000 + 10 * $NUMBER))
FIRSTRIAKPBPORT=$((10000 + 10 * 1 + 7))
CSBASE=$((15000 + 10 * $NUMBER))
RIAKPBPORT=$(($RIAKBASE + 7))
CSPORT=$(($CSBASE + 8))
ADMINPORT=$(($CSBASE + 9))

PLATFORM_BASE_DIR="$BUILD_ROOT/dev/$NAME/riak-cs"

echo "Generating $NAME - node='$NODE' riakpbport=$RIAKPBPORT csport=$CSPORT adminport=$ADMINPORT"
sed -e "s|@PLATFORM_BASE_DIR@|$PLATFORM_BASE_DIR|" \
    -e "s/@NODE@/$NODE/" \
    -e "s/@RIAKPBPORT@/$RIAKPBPORT/" \
    -e "s/@FIRSTRIAKPBPORT@/$FIRSTRIAKPBPORT/" \
    -e "s/@CSPORT@/$CSPORT/" \
    -e "s/@ADMINPORT@/$ADMINPORT/" < $TEMPLATE > $VARFILE
