#!/bin/bash

# Pull environment for this install
source /Users/bryan/work/riak_moss/rel/riak_moss/lib/env.sh

# Make sure the user running this script is the owner and/or su to that user
check_user $@

# Make sure CWD is set to runner run dir
cd $RUNNER_RUN_DIR

# Check the first argument for instructions
case "$1" in
    flush_access)
        # Make sure the local node IS running
        RES=`$NODETOOL ping`
        if [ "$RES" != "pong" ]; then
            echo "Node is not running!"
            exit 1
        fi
        shift

        $NODETOOL rpc riak_moss_usage_console flush_access $@
        ;;
    *)
        echo "Usage: $SCRIPT { flush_access }"
        exit 1
        ;;
esac
