#!/bin/sh

# Identify the script name
SCRIPT=$(basename ${0})

# Pull environment for this install
RUNNER_SCRIPT=${0}

while [ -L $RUNNER_SCRIPT ]; do
    RUNNER_BIN_DIR="$(dirname "$(readlink $RUNNER_SCRIPT)" )"
    RUNNER_SCRIPT_DIR="$(cd $(dirname $RUNNER_SCRIPT) && cd $RUNNER_BIN_DIR && pwd)"
    RUNNER_SCRIPT="$RUNNER_SCRIPT_DIR/$SCRIPT"
done

RUNNER_BASE_DIR=$(cd "$RUNNER_SCRIPT_DIR/.." && pwd)

# Pull environment for this install
. "$RUNNER_BASE_DIR/lib/env.sh"

# Make sure the user running this script is the owner and/or su to that user
check_user $@

# Make sure CWD is set to runner run dir
cd $RUNNER_BASE_DIR

# Check the first argument for instructions
case "$1" in
    flush)
        # Make sure the local node IS running
        node_up_check

        shift

        $NODETOOL rpc riak_cs_access_console flush $@
        ;;
    *)
        echo "Usage: $SCRIPT { flush }"
        exit 1
        ;;
esac
