#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

# Pull environment for this install
. "{{runner_base_dir}}/lib/env.sh"

# Make sure the user running this script is the owner and/or su to that user
check_user $@

# Make sure CWD is set to runner run dir
cd $RUNNER_BASE_DIR

# Identify the script name
SCRIPT=`basename $0`

usage() {
    echo "Usage: $SCRIPT <output_file>"
}

# Check the first argument for instructions
if [ $# -lt 1 ]; then
    usage
    exit 1
fi

# Make sure the local node is running
node_up_check

$NODETOOL rpc_infinity riak_cs_console cluster_info "$@"
