#!/bin/sh

SCRIPT=$(readlink $0 || true)
if [ -z $SCRIPT ]; then
    SCRIPT=$0
fi;

SCRIPT_DIR="$(cd `dirname "$SCRIPT"` && pwd -P)"
RELEASE_ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
REL_NAME="riak-cs"

RPC_HOP=$RELEASE_ROOT_DIR/bin/$REL_NAME

# Check the first argument for instructions
case "$1" in
    list-members|weight|weight-manifest|weight-block|refresh)
        $RPC_HOP rpc riak_cs_multibag_console "$@"
        ;;
    *)
        echo "Usage: $SCRIPT { list-members |  weight | weight-manifest | weight-block | refresh }"
        exit 1
        ;;
esac
