#!/bin/bash

## -------------------------------------------------------------------
##
## riak-cs: Riak CS launcher
##
## Copyright (c) 2021 TI Tokyo.  All Rights Reserved.
##
## This file is provided to you under the Apache License,
## Version 2.0 (the "License"); you may not use this file
## except in compliance with the License.  You may obtain
## a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
## -------------------------------------------------------------------

RUNNER_GEN_DIR={{platform_gen_dir}}
RELX_RIAK={{platform_bin_dir}}/riak-cs
PID_DIR={{pid_dir}}
PIPE_DIR={{pipe_dir}}/   # terminating / (relx treats it as a prefix)

mkdir -p $PID_DIR $PIPE_DIR
chown riak_cs:riak_cs $PID_DIR $PIPE_DIR

function write_pid_file {  # relx doesn't seem to write the pid file, does it?
    local c=3
    sleep 1
    while [[ $c -ne 0 ]]; do
	if [ "`maybe_su ${RELX_RIAK} ping`" = "pong" ]; then
	    maybe_su ${RELX_RIAK} pid >$PID_DIR/riak-cs.pid
            chown root:root $PID_DIR/riak-cs.pid 2&>1 >/dev/null \
		|| true  # systemd wants it to be owned by root
	    break
	fi
	sleep 2
	c=$(($c - 1))
    done
}

function delete_pid_file {
    rm -f $PID_DIR/riak-cs.pid
}

# centos7-based distros have a su that contacts pam and prints the "Last logged in" message
if [ "`cat /etc/redhat-release 2>&1`" = "CentOS Stream release 8" ] ||
   [ "`cat /etc/system-release 2>&1`" = "Amazon Linux release 2 (Karoo)" ]; then
    SU="su --session-command"
else
    SU=su
fi

function maybe_su {
    if [[ $EUID -ne 0 ]]; then
        $*
    else
	$SU riak_cs $*
    fi
}

case "$1" in
    start)
        maybe_su $RELX_RIAK $* -pa {{runner_patch_dir}} \
            && write_pid_file
	test -r $PID_DIR/riak-cs.pid && exit 0
	;;
    console|foreground)
        maybe_su $RELX_RIAK $* -pa {{runner_patch_dir}}
	;;
    stop)
        maybe_su $RELX_RIAK $* \
	    && delete_pid_file
	;;
    admin)
	shift
	maybe_su `which riak-cs-admin` $*
	;;
    debug)
	shift
	maybe_su `which riak-cs-debug` $*
	;;
    *)
        ESCAPED_ARGS=`echo "$@" | sed -e 's/\([\\\(\\\){}"\x27]\)/\\\\\1/g'`
        maybe_su $RELX_RIAK $ESCAPED_ARGS
        ;;
esac
